python train_cate.py conv_backbone="OpenPose" dataset="Custom" pose_dataset.processed_csv="dataset/keypoints_OP_5.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=0 val.camera_type=0 test.camera_type=0 extract_keypoints=True output_dim=9 train.devices=[0] train.patience=30 openpose_detect.hands=False
python train_cate.py conv_backbone="OpenPose" dataset="Custom" pose_dataset.processed_csv="dataset/keypoints_OP_5.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=1 val.camera_type=1 test.camera_type=1 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30 openpose_detect.hands=False
python train_cate.py conv_backbone="OpenPose" dataset="Custom" pose_dataset.processed_csv="dataset/keypoints_OP_5.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset_resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30 openpose_detect.hands=False
python train_cate.py conv_backbone="OpenPose" dataset="Custom" pose_dataset.processed_csv="dataset/keypoints_OP_5_hand.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=0 val.camera_type=0 test.camera_type=0 extract_keypoints=True output_dim=9 train.devices=[0] train.patience=30 openpose_detect.hands=True
python train_cate.py conv_backbone="OpenPose" dataset="Custom" pose_dataset.processed_csv="dataset/keypoints_OP_5_hand.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=1 val.camera_type=1 test.camera_type=1 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30 openpose_detect.hands=True
python train_cate.py conv_backbone="OpenPose" dataset="Custom" pose_dataset.processed_csv="dataset/keypoints_OP_5_hand.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30 openpose_detect.hands=True

# python train_cate.py conv_backbone="OpenPose" dataset="KTH" KTH_dataset.processed_csv="dataset/KTH_OP_5.csv" KTH_dataset.fps=5 KTH_dataset.resize_w=160 KTH_dataset.resize_h=120 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 KTH_dataset.train=[11,12,13,14,15,16,17,18] KTH_dataset.val=[22,2,3,5,6,7,10,8,9] KTH_dataset.test=[19,20,21,23,24,25,1,4] extract_keypoints=True output_dim=6 train.devices=[0] train.patience=30
# python train_cate.py conv_backbone="OpenPose" dataset="KTH" KTH_dataset.processed_csv="dataset/KTH_OP_5_hands.csv" KTH_dataset.fps=5 KTH_dataset.resize_w=160 KTH_dataset.resize_h=128 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 KTH_dataset.train=[11,12,13,14,15,16,17,18] KTH_dataset.val=[22,2,3,5,6,7,10,8,9] KTH_dataset.test=[19,20,21,23,24,25,1,4] extract_keypoints=True output_dim=6 train.devices=[0] train.patience=30

