python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="n" pose_dataset.processed_csv="dataset/keypoints_YOLO_n_5_0.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epoch=200 train.lr=0.000001 train.patient_ids=[123,243] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=0 val.camera_type=0 test.camera_type=0 extract_keypoints=True  
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="n" pose_dataset.processed_csv="dataset/keypoints_YOLO_n_5_1.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epoch=200 train.lr=0.000001 train.patient_ids=[123,243] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=1 val.camera_type=1 test.camera_type=1 extract_keypoints=True  
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="n" pose_dataset.processed_csv="dataset/keypoints_YOLO_n_5_2.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epoch=200 train.lr=0.000001 train.patient_ids=[123,243] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=True  

python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="m" pose_dataset.processed_csv="dataset/keypoints_YOLO_m_5_0.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epoch=200 train.lr=0.000001 train.patient_ids=[123,243] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=0 val.camera_type=0 test.camera_type=0 extract_keypoints=True  
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="m" pose_dataset.processed_csv="dataset/keypoints_YOLO_m_5_1.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epoch=200 train.lr=0.000001 train.patient_ids=[123,243] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=1 val.camera_type=1 test.camera_type=1 extract_keypoints=True  
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="m" pose_dataset.processed_csv="dataset/keypoints_YOLO_m_5_2.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epoch=200 train.lr=0.000001 train.patient_ids=[123,243] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=True  

python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="x" pose_dataset.processed_csv="dataset/keypoints_YOLO_x_5_0.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epoch=200 train.lr=0.000001 train.patient_ids=[123,243] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=0 val.camera_type=0 test.camera_type=0 extract_keypoints=True  
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="x" pose_dataset.processed_csv="dataset/keypoints_YOLO_x_5_1.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epoch=200 train.lr=0.000001 train.patient_ids=[123,243] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=1 val.camera_type=1 test.camera_type=1 extract_keypoints=True  
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="x" pose_dataset.processed_csv="dataset/keypoints_YOLO_x_5_2.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epoch=200 train.lr=0.000001 train.patient_ids=[123,243] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=True  
