python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="n" pose_dataset.processed_csv="dataset/keypoints_YOLO_n_5_0.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=0 val.camera_type=0 test.camera_type=0 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="n" pose_dataset.processed_csv="dataset/keypoints_YOLO_n_5_1.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=1 val.camera_type=1 test.camera_type=1 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="n" pose_dataset.processed_csv="dataset/keypoints_YOLO_n_5_2.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30

python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="m" pose_dataset.processed_csv="dataset/keypoints_YOLO_m_5_0.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=0 val.camera_type=0 test.camera_type=0 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="m" pose_dataset.processed_csv="dataset/keypoints_YOLO_m_5_1.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=1 val.camera_type=1 test.camera_type=1 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="m" pose_dataset.processed_csv="dataset/keypoints_YOLO_m_5_2.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30

python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="x" pose_dataset.processed_csv="dataset/keypoints_YOLO_x_5_0.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=0 val.camera_type=0 test.camera_type=0 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="x" pose_dataset.processed_csv="dataset/keypoints_YOLO_x_5_1.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=1 val.camera_type=1 test.camera_type=1 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="x" pose_dataset.processed_csv="dataset/keypoints_YOLO_x_5_2.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30

python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="n" pose_dataset.processed_csv="dataset/keypoints_YOLO_n_5_2.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,345] val.patient_ids=[234] test.patient_ids=[234] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="m" pose_dataset.processed_csv="dataset/keypoints_YOLO_m_5_2.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[234,345] val.patient_ids=[123] test.patient_ids=[123] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="Custom" yolo.model_size="x" pose_dataset.processed_csv="dataset/keypoints_YOLO_x_5_2.csv" pose_dataset.fps=5 pose_dataset.resize_w=640 pose_dataset.resize_h=480 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 train.patient_ids=[123,234] val.patient_ids=[345] test.patient_ids=[345] train.camera_type=2 val.camera_type=2 test.camera_type=2 extract_keypoints=False output_dim=9 train.devices=[0] train.patience=30


python train_cate.py conv_backbone="YOLO" dataset="KTH" yolo.model_size="n" KTH_dataset.processed_csv="dataset/KTH_YOLO_n_5.csv" KTH_dataset.fps=5 KTH_dataset.resize_w=160 KTH_dataset.resize_h=128 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 KTH_dataset.train=[11,12,13,14,15,16,17,18] KTH_dataset.val=[22,2,3,5,6,7,10,8,9] KTH_dataset.test=[19,20,21,23,24,25,1,4] extract_keypoints=True output_dim=6 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="KTH" yolo.model_size="m" KTH_dataset.processed_csv="dataset/KTH_YOLO_m_5.csv" KTH_dataset.fps=5 KTH_dataset.resize_w=160 KTH_dataset.resize_h=128 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 KTH_dataset.train=[11,12,13,14,15,16,17,18] KTH_dataset.val=[22,2,3,5,6,7,10,8,9] KTH_dataset.test=[19,20,21,23,24,25,1,4] extract_keypoints=True output_dim=6 train.devices=[0] train.patience=30
python train_cate.py conv_backbone="YOLO" dataset="KTH" yolo.model_size="x" KTH_dataset.processed_csv="dataset/KTH_YOLO_x_5.csv" KTH_dataset.fps=5 KTH_dataset.resize_w=160 KTH_dataset.resize_h=128 train.batch_size=8 train.max_epochs=1000 train.lr=0.000001 KTH_dataset.train=[11,12,13,14,15,16,17,18] KTH_dataset.val=[22,2,3,5,6,7,10,8,9] KTH_dataset.test=[19,20,21,23,24,25,1,4] extract_keypoints=True output_dim=6 train.devices=[0] train.patience=30
