defaults:
  - _self_
  - dataset
  
wandb:
  entity: "c-bruchi-university-of-pisa"
  project: "pat-mon"

task: 'classification'
model : null
seed: -1

in_channels: 3
depth: 20
width: 1920
height: 1080
output_dim : 9
extract_keypoints: True
conv_backbone: "YOLO"

yolo:
  model_size: "s"
openpose:
  detect_hands: True
  detect_face: True


pose_dataset:
  path: dataset/position
  csv_path: dataset/position.csv
  processed_csv: dataset/keypoints/keypoints_YOLO_s_2_1.csv
  resize_h: 480
  resize_w: 640
  fps: 2

train:
  save_path: "./models/"
  batch_size: 1
  lr: 1e-5
  max_epochs: 5
  num_workers: 1
  patient_ids: [123]
  camera_type: 1
  accelerator: "cpu"
  devices: 1
  seed: -1

val:
  patient_ids: [234]
  camera_type: 1

test:
  patient_ids: [345]
  camera_type: 1

log:  
  path: "./logs/"

hydra.run.dir: .
hydra.output_subdir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d_%H-%M-%S}

