defaults:
  - _self_
  - dataset
  
wandb:
  entity: "c-bruchi-university-of-pisa"
  project: "pat-mon"

task: 'classification'
model : null
seed: -1

in_channels: 3
depth: 20
width: 1920
height: 1080
output_dim : 9
extract_keypoints: True 
conv_backbone: "CNN3D"

yolo:
  model_size: "m"
openpose:
  detect_hands: False
  detect_face: True


pose_dataset:
  path: dataset/position
  csv_path: dataset/position.csv
  processed_csv: dataset/keypoints/keypoints_CNN_3_2.csv
  resize_h: 256
  resize_w: 256
  fps: 3

train:
  save_path: "./models/"
  batch_size: 1
  lr: 1e-5
  max_epochs: 5
  num_workers: 1
  patient_ids: [123]
  camera_type: 2
  accelerator: "cpu"
  devices: 1
  seed: -1

val:
  patient_ids: [234]
  camera_type: 2

test:
  patient_ids: [345]
  camera_type: 2

log:  
  path: "./logs/"

hydra.run.dir: .
hydra.output_subdir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d_%H-%M-%S}

