defaults:
  - _self_
  - privacy

privacy:
  age: True
  gender: True
  skin_color: True
  
task: 'classification'
model : null
seed: -1

input_shape : [1, 3, 20, 256, 256]
output_dim : 9

pose_dataset:
  path: ./dataset/position
  csv_path: ./dataset/position.csv
  resize: 224
  fps: 5

train:
  save_path: "./models/"
  batch_size: 32
  lr: 1e-5
  max_epochs: 100
  num_workers: 1
  patient_ids: [123, 234]
  camera_type: 0
  accelerator: "cpu"
  devices: 1
  seed: -1

val:
  patient_ids: [345]
  camera_type: 0

test:
  patient_ids: [345]
  camera_type: 0


log:  
  path: "./logs/"


hydra.run.dir: .
hydra.output_subdir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d_%H-%M-%S}

wandb:
  wandb:
  entity: marcoparla
  project: patient-monitoring
