defaults:
  - _self_
  - dataset
  - KTH

wandb:
  entity: "c-bruchi-university-of-pisa"
  project: "pat-mon"

task: 'classification'
model : null
seed: -1

in_channels: 3
depth: 20
width: 1920
height: 1080
output_dim : 9
extract_keypoints: True
conv_backbone: "CNN3D"
end: "mlp"
dataset: "KTH"


yolo:
  model_size: "n"
openpose:
  detect_hands: False
  detect_face: False


pose_dataset:
  path: dataset/position
  csv_path: dataset/position.csv
  processed_csv: dataset/keypoints_YOLO_x_3.csv
  resize_h: 480
  resize_w: 640
  fps: 3


KTH_dataset:
  path: dataset/KTH
  csv_path: dataset/KTH_cut.csv
  resize_h: 120
  resize_w: 160
  fps: 5
  train: [11, 12, 13, 14, 15, 16, 17, 18]
  test: [19, 20, 21, 23, 24, 25, 01, 04]
  val: [22, 02, 03, 05, 06, 07, 08, 09, 10]

train:
  save_path: "./models/"
  batch_size: 8
  lr: 1e-6
  max_epochs: 100
  num_workers: 1
  patient_ids: [123,234]
  camera_type: 2
  accelerator: "gpu"
  devices: [1]
  seed: -1
  patience: 15

val:
  patient_ids: [345]
  camera_type: 2

test:
  patient_ids: [345]
  camera_type: 2

log:  
  path: "./logs/"

hydra.run.dir: .
hydra.output_subdir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d_%H-%M-%S}

