defaults:
  - _self_
  - privacy
  - dataset
  - wandb
  
task: 'privacy'
model : null
seed: -1

in_channels: 3

train:
  save_path: "./models/"
  batch_size: 8
  max_epochs: 30
  num_workers: 1
  patient_ids: [123, 234]
  camera_type: 0
  accelerator: "gpu"
  devices: [0]
  early_stopping: False
  patience: 10
  seed: -1

val:
  patient_ids: [345]
  camera_type: 0

test:
  patient_ids: [345]
  camera_type: 0

learning_rates:
  pose: 1e-5
  privatizer: 1e-5
  privacy: 1e-5

hydra.run.dir: .
hydra.output_subdir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d_%H-%M-%S}
