defaults:
  - _self_
  - privacy
  - dataset

privacy:
  age: True
  gender: True
  skin_color: True
  
task: 'classification'
model : null
seed: -1

in_channels: 3
depth: 20
width: 256
height: 256
output_dim : 10

pose_dataset:
  path: ./dataset/position
  csv_path: ./dataset/position.csv
  resize: 256
  fps: 20

train:
  save_path: "./models/"
  batch_size: 128
  lr: 1e-5
  max_epochs: 10
  num_workers: 1
  patient_ids: [123, 234]
  camera_type: 0
  accelerator: "gpu"
  devices: [0]
  seed: -1

val:
  patient_ids: [345]
  camera_type: 0

test:
  patient_ids: [345]
  camera_type: 0

log:  
  path: "./logs/"

hydra.run.dir: .
hydra.output_subdir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d_%H-%M-%S}

wandb:
  entity: "baffobello14-universit-di-pisa"
  project: "patient-monitoring"
