privacy_attributes:
  skin_color: 4
  gender: 1
  age: 1

privacy_map:
  white: 0
  brown: 1
  yellow: 2
  black: 3
  male: 0
  female: 1

privacy_model_type: "VIDEO_PRIVATIZER"

loss_weights:
  alpha: 1.0
  beta: 0.5

path_privacy: "./data/"
